name: practice the secret\
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch: 
permissions: 
  contents: read
jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: The secret print
        run: |
          echo "The value of${{ secrets.DB_PASSWORD }}"
          echo "The value of ${{secrets.API_KEY }}"
          echo "The value of $(secrets.AZURE_CLIENT_ID}}
          echo "The value of ${{vars.DB_HOST}}"
          echo "The balue of ${{vars.DB_NAME}}"
