name: Practice matrix 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: 
jobs:
  matrix_job:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        Node:
          - "18"
          - "20"
          - "22"
        exclude:
          - os: windows-latest
            Node: "18"
        include:
          - os: ubuntu-latest
            Node: "21"
            experiemental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experiemental == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: The Node version
        run: | 
          sleep 2
          echo "The os and the node version combo is ${{ matrix.os }} and ${{ matrix.Node }}"
  
    
