name: practice-problem-2
env:
  APP_NAME: ram-practice-project
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    env:
      ENVIRONMENT: ram
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Environment variable level check
        env:
          REGION: centralindia 
        run: |
          echo "The workflow level varible : ${{env.APP_NAME}}"
          echo "The job level varible : ${{env.ENVIRONMENT}}"
          echo "The step level varible : ${{env.REGION}}"
          echo "The repo name : ${{ github.repository }}"
          echo "The workflow name :${{ github.workflow }}"
          echo "The runner os :${{ runner.os }}"
          echo "The runner arch :${{ runner.arch }}"
        
    
