name: Practice Problem 4
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  buildapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: lint the code
        run: |
          echo "The code is being lint"
      - name: 
    
