name: Testing Secret Variables

on:
  workflow_dispatch
env:
  ACTIONS_STEP_DEBUG: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Secret Variable"
        run: |
          echo "Secret Value : ${{ secrets.RAM }}"
